filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/data/raw/*.log
      - /usr/share/filebeat/data/raw/*.jsonl

output.kafka:
  hosts: ["kafka:9092"]
  topic: "payment-logs"
  required_acks: 1
